branch-defaults:
  default:
    environment: pf-services
global:
  application_name: pf-app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
